version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sohamapi"
s3_bucket = "sohamserverlessapi"
s3_prefix = "sohamserverlessapi"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
image_repositories = []
#parameter_overrides = "StageName=\"stage\""
parameter_overrides = "StageName=Dev"
