AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  soham_api

  API for managing projects and users, deployed using AWS SAM.

Parameters:
  StageName:
    Type: String
    Default: Dev

Resources:
  ProjectsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ProjectsFunction-${StageName}
      CodeUri: projects
      Handler: app.projectHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Tracing: Active
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: projects
          POWERTOOLS_METRICS_NAMESPACE: soham_api
          LOG_LEVEL: INFO
          MONGO_URI: "mongodb+srv://SohamDev:4Y4DjfJbXAGqJK47@soham-dev.eagjctq.mongodb.net/SohamDB?retryWrites=true&w=majority&appName=Soham-Dev"
          DB_NAME: "SohamDB"
      Events:
        ProjectsApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /projects
            Method: ANY
        ProjectsPutApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /projects/{id}
            Method: ANY
        ProjectEventDeleteApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /projects/events/{eventId}
            Method: ANY
        ProjectEventsApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /projects/{id}/events
            Method: ANY
        ProjectUsersApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /projects/{id}/users
            Method: ANY

  UsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub UsersFunction-${StageName}
      CodeUri: users
      Handler: app.userHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Tracing: Active
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: users
          POWERTOOLS_METRICS_NAMESPACE: soham_api
          LOG_LEVEL: INFO
          MONGO_URI: "mongodb+srv://SohamDev:4Y4DjfJbXAGqJK47@soham-dev.eagjctq.mongodb.net/SohamDB?retryWrites=true&w=majority&appName=Soham-Dev"
          DB_NAME: "SohamDB"
      Events:
        UsersApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /users
            Method: ANY

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: SohamApi-backend
      StageName: !Sub MyApi-${StageName}
      Cors:
        AllowMethods: "'GET, POST, PUT, DELETE, OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
        MaxAge: 86400
